In [19]:
# Import libraries

import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import re

In [20]:
# Import the functions

from functions_py_file import *

In [21]:
# Read in data

adjacency_matrix = pd.read_csv("adjacency_matrix2.csv", header=0, index_col=0)

multilevel = pd.read_csv("multilevel2.csv", header=0, index_col=0) 

## Fake test

In [22]:
# Clean the adjacency matrix

adjacency_matrix = clean_adjacency_mat(adjacency_matrix)
adjacency_matrix

Everything  CSF_508_5  Myelencephalon_507_5  \
Everything                     0          1                     1   
CSF_508_5                      0          0                     0   
Myelencephalon_507_5           0          0                     0   
Metencephalon_506_5            0          0                     0   
Mesencephalon_505_5            0          0                     0   
...                          ...        ...                   ...   
SFG_pole_L_5_1                 0          0                     0   
SFG_PFC_R_4_1                  0          0                     0   
SFG_PFC_L_3_1                  0          0                     0   
SFG_R_2_1                      0          0                     0   
SFG_L_1_1                      0          0                     0   

                      Metencephalon_506_5  Mesencephalon_505_5  \
Everything                              1                    1   
CSF_508_5                               0                    0   
Myelencephalon_507_5                    0                    0   
Metencephalon_506_5                     0                    0   
Mesencephalon_505_5                     0                    0   
...                                   ...                  ...   
SFG_pole_L_5_1                          0                    0   
SFG_PFC_R_4_1                           0                    0   
SFG_PFC_L_3_1                           0                    0   
SFG_R_2_1                               0                    0   
SFG_L_1_1                               0                    0   

                      Diencephalon_R_504_5  Diencephalon_L_503_5  \
Everything                               1                     1   
CSF_508_5                                0                     0   
Myelencephalon_507_5                     0                     0   
Metencephalon_506_5                      0                     0   
Mesencephalon_505_5                      0                     0   
...                                    ...                   ...   
SFG_pole_L_5_1                           0                     0   
SFG_PFC_R_4_1                            0                     0   
SFG_PFC_L_3_1                            0                     0   
SFG_R_2_1                                0                     0   
SFG_L_1_1                                0                     0   

                      Telencephalon_R_502_5  Telencephalon_L_501_5  \
Everything                                1                      1   
CSF_508_5                                 0                      0   
Myelencephalon_507_5                      0                      0   
Metencephalon_506_5                       0                      0   
Mesencephalon_505_5                       0                      0   
...                                     ...                    ...   
SFG_pole_L_5_1                            0                      0   
SFG_PFC_R_4_1                             0                      0   
SFG_PFC_L_3_1                             0                      0   
SFG_R_2_1                                 0                      0   
SFG_L_1_1                                 0                      0   

                      Sulcus_R_500_4  ...  MFG_DPFC_R_10_1  MFG_DPFC_L_9_1  \
Everything                         0  ...                0               0   
CSF_508_5                          1  ...                0               0   
Myelencephalon_507_5               0  ...                0               0   
Metencephalon_506_5                0  ...                0               0   
Mesencephalon_505_5                0  ...                0               0   
...                              ...  ...              ...             ...   
SFG_pole_L_5_1                     0  ...                0               0   
SFG_PFC_R_4_1                      0  ...                0               0   
SFG_PFC_L_3_1                      0  ..

In [23]:
# Clean the multilevel lookup table

multilevel = clean_multilevel(multilevel, adjacency_matrix)
multilevel

Number             Structure Immediate.parent  \
509       1            Everything              NaN   
508       2             CSF_508_5       Everything   
507       3  Myelencephalon_507_5       Everything   
506       4   Metencephalon_506_5       Everything   
505       5   Mesencephalon_505_5       Everything   
..      ...                   ...              ...   
5       505        SFG_pole_L_5_1      SFG_L_290_2   
4       506         SFG_PFC_R_4_1      SFG_R_291_2   
3       507         SFG_PFC_L_3_1      SFG_L_290_2   
2       508             SFG_R_2_1      SFG_R_291_2   
1       509             SFG_L_1_1      SFG_L_290_2   

                              Immediate.child.children  
509  Telencephalon_L_501_5, Telencephalon_R_502_5, ...  
508    Ventricle_498_4, Sulcus_L_499_4, Sulcus_R_500_4  
507     Myelencephalon_L_494_4, Myelencephalon_R_495_4  
506       Metencephalon_L_492_4, Metencephalon_R_493_4  
505       Mesencephalon_L_490_4, Mesencephalon_R_491_4  
..                                                 ...  
5                                                  NaN  
4                                                  NaN  
3                                                  NaN  
2                                                  NaN  
1                                                  NaN  

[509 rows x 4 columns]

In [24]:
# Create the subset adjacency matrix

subset_leaf_list = ["Amyg_L_73_1", "Hippo_L_75_1"]
subset = subset_matrix_creator(subset_leaf_list, adjacency_matrix, multilevel)
subset

Everything  Telencephalon_L_501_5  \
Everything                       0                      1   
Telencephalon_L_501_5            0                      0   
CerebralCortex_L_482_4           0                      0   
Limbic_L_434_3                   0                      0   
Hippo_L_338_2                    0                      0   
Amyg_L_336_2                     0                      0   
Hippo_L_75_1                     0                      0   
Amyg_L_73_1                      0                      0   

                        CerebralCortex_L_482_4  Limbic_L_434_3  Hippo_L_338_2  \
Everything                                   0               0              0   
Telencephalon_L_501_5                        1               0              0   
CerebralCortex_L_482_4                       0               1              0   
Limbic_L_434_3                               0               0              1   
Hippo_L_338_2                                0               0              0   
Amyg_L_336_2                                 0               0              0   
Hippo_L_75_1                                 0               0              0   
Amyg_L_73_1                                  0               0              0   

                        Amyg_L_336_2  Hippo_L_75_1  Amyg_L_73_1  
Everything                         0             0            0  
Telencephalon_L_501_5              0             0            0  
CerebralCortex_L_482_4             0             0            0  
Limbic_L_434_3                     1             0            0  
Hippo_L_338_2                      0             1            0  
Amyg_L_336_2                       0             0            1  
Hippo_L_75_1                       0             0            0  
Amyg_L_73_1                        0             0            0

In [25]:
# Create the descendants matrix

descendants = adjacency_descendants(subset, N=20, mu=3.0)
descendants

array([[False,  True,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [26]:
# Create the ancestors matrix

ancestors = adjacency_ancestors(subset, N=20, mu=3.0)
ancestors

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [ True,  True, False, False, False, False, False, False],
       [ True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False,  True, False, False]])

In [9]:
# Generate simulated data

generate_simulated_data(filename="test1_data", subset=subset, case=2, n_repeats=10, N=20, mu=3.0)
generate_simulated_data(filename="test2_data", subset=subset, case=3, n_repeats=5, N=20, mu=3.0)
generate_simulated_data(filename="test3_data", subset=subset, case=4, n_repeats=15, N=20, mu=3.0)
generate_simulated_data(filename="test4_data", subset=subset, case=1, n_repeats=20, N=20, mu=3.0)

# Viewing the contents of the generated data file to check
test = np.load("test1_data.npz")

print("\033[1m" + "X" + "\033[0m") 
print(test["X"])

print("\033[1m" + "Z" + "\033[0m") 
print(test["Z"])

print("\033[1m" + "G" + "\033[0m") 
print(test["G"])

X
[[ 3.71386161  2.38670855]
 [ 3.67272723 -1.41209934]
 [ 2.57156945 -0.28371132]
 [ 1.90238622  1.60425034]
 [ 2.32691052  0.03402707]
 [ 3.12365613 -0.54317417]
 [ 3.47839864  0.94098628]
 [ 3.21844748  1.26154165]
 [ 3.90905845  0.56082971]
 [ 3.04167366 -0.28364028]
 [ 0.55134619  0.11449201]
 [ 0.04212985 -0.11579027]
 [ 1.29275125 -2.24426779]
 [-0.65695559  1.44335339]
 [-0.21928461 -0.01992268]
 [ 1.50847049 -0.25746049]
 [ 0.15933447 -1.16571544]
 [ 0.21309726  2.08065704]
 [ 0.2297345   0.13756753]
 [ 0.16699821  0.38151913]]
Z
[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 

In [10]:
# Permutation testing

permutation_testing(filename_old="test1_data.npz", filename_new = "test1_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test2_data.npz", filename_new = "test2_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, clip=0.0001, initial_prob = 0.5)
permutation_testing(filename_old="test3_data.npz", filename_new = "test3_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.25, clip=0.01)
permutation_testing(filename_old="test4_data.npz", filename_new = "test4_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.75, clip=0.001)

# Viewing the contents of the .npz files to check
# Using "\033[1m" and "\033[0m" to get bold text printed

filename = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"]
for i in range(0, 4):
    # Assign the file to an object called "test," which is a dictionary object
    test = np.load(filename[i])
    print("\033[1m" + filename[i] + "\033[0m") 

    # Print the values corresponding to each key
    print("\033[1m" + "p-values:" + "\033[0m")
    print(test["pval"])
    
    print("\033[1m" + "names:" + "\033[0m")
    print(test["names"])
    
    print("\033[1m" + "posterior:" + "\033[0m")
    print(test["posterior"])
    
    print("\033[1m" + "strings:" + "\033[0m")
    print(test["strings"])

test1_results.npz
p-values:
[0.  0.  0.  0.  0.  0.  0.3 0.3]
names:
['Limbic_L_434_3' 'CerebralCortex_L_482_4' 'Telencephalon_L_501_5'
 'Everything' 'Hippo_L_75_1' 'Hippo_L_338_2' 'Amyg_L_73_1' 'Amyg_L_336_2']
posterior:
[0.9999582  0.9999582  0.9999582  0.9999582  0.99995474 0.99995474
 0.07209838 0.07209838]
strings:
['Everything, P[Z=1|X]=0.9999582000703212, p=0.0'
 'Telencephalon_L_501_5, P[Z=1|X]=0.9999582000703212, p=0.0'
 'CerebralCortex_L_482_4, P[Z=1|X]=0.9999582000703212, p=0.0'
 'Limbic_L_434_3, P[Z=1|X]=0.9999582000703212, p=0.0'
 'Hippo_L_338_2, P[Z=1|X]=0.9999547360405941, p=0.0'
 'Hippo_L_75_1, P[Z=1|X]=0.9999547360405941, p=0.0'
 'Amyg_L_336_2, P[Z=1|X]=0.07209838140488883, p=0.3'
 'Amyg_L_73_1, P[Z=1|X]=0.07209838140488883, p=0.3']
test2_results.npz
p-values:
[0. 0. 0. 0. 0. 0. 0. 0.]
names:
['Limbic_L_434_3' 'CerebralCortex_L_482_4' 'Telencephalon_L_501_5'
 'Everything' 'Amyg_L_73_1' 'Amyg_L_336_2' 'Hippo_L_75_1' 'Hippo_L_338_2']
posterior:
[1.         1.         1. 

In [11]:
# False positive rate

false_positive_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], n_repeats = 10)

0.3

In [12]:
# False negative rate

print("\033[1m" + "Testing case 2:" + "\033[0m")
print(false_negative_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], case=2, n_repeats=10))

print("\033[1m" + "Testing case 3:" + "\033[0m")
print(false_negative_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], case=3, n_repeats=10))

print("\033[1m" + "Testing case 4:" + "\033[0m")
print(false_negative_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], case=4, n_repeats=10))

Testing case 2:
                Structure  False negative rate
0              Everything                  0.7
1   Telencephalon_L_501_5                  0.7
2  CerebralCortex_L_482_4                  0.7
3          Limbic_L_434_3                  0.7
4           Hippo_L_338_2                  0.8
6            Hippo_L_75_1                  0.8
Testing case 3:
                Structure  False negative rate
0              Everything                  0.7
1   Telencephalon_L_501_5                  0.7
2  CerebralCortex_L_482_4                  0.7
3          Limbic_L_434_3                  0.7
4           Hippo_L_338_2                  0.8
5            Amyg_L_336_2                  0.9
6            Hippo_L_75_1                  0.8
7             Amyg_L_73_1                  0.9
Testing case 4:
                Structure  False negative rate
0              Everything                  0.7
1   Telencephalon_L_501_5                  0.7
2  CerebralCortex_L_482_4                  0.7
3          L

## Real test

Original parameters:

* Clip probabilities at 0.999 and 0.001
* Run 20 iterations of the EM algorithm
* Initial probabilities are 0.5
* `n_repeats = 1000` Number of repeats per case per experiment
* `n_perm = 1000` Number of permutations when permutation testing

We need to run all 4 cases so we can calculate both false positive rate and false negative rate

**Question**: Since the file names are user inputs, is there a quicker way to obtain a list that contains thousands of file names?

In [15]:
case_1 = []

for i in range(1, 9):
    for j in range(0, 100):
        if j < 10:
            string = "fwer_experiments_test/case_1_experiment_" + str(i) + "_repeat_" + "00" + str(j) + ".npz"
        elif j < 100:
            string = "fwer_experiments_test/case_1_experiment_" + str(i) + "_repeat_" + "0" + str(j) + ".npz"
        case_1.append(string)

case_1[0], case_1[99]

('fwer_experiments_test/case_1_experiment_1_repeat_000.npz',
 'fwer_experiments_test/case_1_experiment_1_repeat_099.npz')

In [16]:
case_2 = []

for i in range(1, 9):
    for j in range(0, 100):
        if j < 10:
            string = "fwer_experiments_test/case_2_experiment_" + str(i) + "_repeat_" + "00" + str(j) + ".npz"
        elif j < 100:
            string = "fwer_experiments_test/case_2_experiment_" + str(i) + "_repeat_" + "0" + str(j) + ".npz"
        case_2.append(string)

case_2[0], case_2[99]

('fwer_experiments_test/case_2_experiment_1_repeat_000.npz',
 'fwer_experiments_test/case_2_experiment_1_repeat_099.npz')

In [17]:
case_3 = []

for i in range(1, 9):
    for j in range(0, 100):
        if j < 10:
            string = "fwer_experiments_test/case_3_experiment_" + str(i) + "_repeat_" + "00" + str(j) + ".npz"
        elif j < 100:
            string = "fwer_experiments_test/case_3_experiment_" + str(i) + "_repeat_" + "0" + str(j) + ".npz"
        case_3.append(string)

case_3[0], case_3[99]

('fwer_experiments_test/case_3_experiment_1_repeat_000.npz',
 'fwer_experiments_test/case_3_experiment_1_repeat_099.npz')

In [18]:
case_4 = []

for i in range(1, 9):
    for j in range(0, 100):
        if j < 10:
            string = "fwer_experiments_test/case_4_experiment_" + str(i) + "_repeat_" + "00" + str(j) + ".npz"
        elif j < 100:
            string = "fwer_experiments_test/case_4_experiment_" + str(i) + "_repeat_" + "0" + str(j) + ".npz"
        case_4.append(string)

case_4[0], case_4[99]

('fwer_experiments_test/case_4_experiment_1_repeat_000.npz',
 'fwer_experiments_test/case_4_experiment_1_repeat_099.npz')

In [36]:
# Generate simulated data

generate_simulated_data(filename="test1_data", subset=subset, case=1, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test2_data", subset=subset, case=2, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test3_data", subset=subset, case=3, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test4_data", subset=subset, case=4, n_repeats=1000, N=20, mu=3.0)

In [37]:
# Permutation testing

permutation_testing(filename_old="test1_data.npz", filename_new = "test1_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test2_data.npz", filename_new = "test2_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, clip=0.001, initial_prob = 0.5)
permutation_testing(filename_old="test3_data.npz", filename_new = "test3_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test4_data.npz", filename_new = "test4_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)

KeyboardInterrupt: 

In [31]:
# False positive rate

false_positive_rate(subset, file_names = ["test1_results.npz"], n_repeats = 1000)

0.0

In [32]:
# False positive rate

false_positive_rate(subset, file_names = ["test2_results.npz"], n_repeats = 1000)

0.01

In [33]:
# False negative rate

false_negative_rate(subset, file_names = ["test2_results.npz"], case=2, n_repeats=1000)

Structure  False negative rate
0              Everything                 0.99
1   Telencephalon_L_501_5                 0.99
2  CerebralCortex_L_482_4                 0.99
3          Limbic_L_434_3                 0.99
4           Hippo_L_338_2                 0.99
6            Hippo_L_75_1                 0.99

In [34]:
# False negative rate

false_negative_rate(subset, file_names = ["test3_results.npz"], case=3, n_repeats=1000)

Structure  False negative rate
0              Everything                 0.99
1   Telencephalon_L_501_5                 0.99
2  CerebralCortex_L_482_4                 0.99
3          Limbic_L_434_3                 0.99
4           Hippo_L_338_2                 0.99
5            Amyg_L_336_2                 0.99
6            Hippo_L_75_1                 0.99
7             Amyg_L_73_1                 0.99

In [35]:
# False negative rate

false_negative_rate(subset, file_names = ["test4_results.npz"], case=4, n_repeats=1000)

Structure  False negative rate
0              Everything                 0.99
1   Telencephalon_L_501_5                 0.99
2  CerebralCortex_L_482_4                 0.99
3          Limbic_L_434_3                 0.99
4           Hippo_L_338_2                 0.99
5            Amyg_L_336_2                 0.99
6            Hippo_L_75_1                 0.99
7             Amyg_L_73_1                 0.99