In [1]:
# Import libraries

import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import re
from glob import glob
import os

In [2]:
# Import the functions

from functions_py_file import *

In [3]:
# Read in data

adjacency_matrix = pd.read_csv("adjacency_matrix2.csv", header=0, index_col=0)

multilevel = pd.read_csv("multilevel2.csv", header=0, index_col=0) 

## Fake test

In [4]:
# Clean the adjacency matrix

adjacency_matrix = clean_adjacency_mat(adjacency_matrix)
adjacency_matrix

Everything  CSF_508_5  Myelencephalon_507_5  \
Everything                     0          1                     1   
CSF_508_5                      0          0                     0   
Myelencephalon_507_5           0          0                     0   
Metencephalon_506_5            0          0                     0   
Mesencephalon_505_5            0          0                     0   
...                          ...        ...                   ...   
SFG_pole_L_5_1                 0          0                     0   
SFG_PFC_R_4_1                  0          0                     0   
SFG_PFC_L_3_1                  0          0                     0   
SFG_R_2_1                      0          0                     0   
SFG_L_1_1                      0          0                     0   

                      Metencephalon_506_5  Mesencephalon_505_5  \
Everything                              1                    1   
CSF_508_5                               0                    0   
Myelencephalon_507_5                    0                    0   
Metencephalon_506_5                     0                    0   
Mesencephalon_505_5                     0                    0   
...                                   ...                  ...   
SFG_pole_L_5_1                          0                    0   
SFG_PFC_R_4_1                           0                    0   
SFG_PFC_L_3_1                           0                    0   
SFG_R_2_1                               0                    0   
SFG_L_1_1                               0                    0   

                      Diencephalon_R_504_5  Diencephalon_L_503_5  \
Everything                               1                     1   
CSF_508_5                                0                     0   
Myelencephalon_507_5                     0                     0   
Metencephalon_506_5                      0                     0   
Mesencephalon_505_5                      0                     0   
...                                    ...                   ...   
SFG_pole_L_5_1                           0                     0   
SFG_PFC_R_4_1                            0                     0   
SFG_PFC_L_3_1                            0                     0   
SFG_R_2_1                                0                     0   
SFG_L_1_1                                0                     0   

                      Telencephalon_R_502_5  Telencephalon_L_501_5  \
Everything                                1                      1   
CSF_508_5                                 0                      0   
Myelencephalon_507_5                      0                      0   
Metencephalon_506_5                       0                      0   
Mesencephalon_505_5                       0                      0   
...                                     ...                    ...   
SFG_pole_L_5_1                            0                      0   
SFG_PFC_R_4_1                             0                      0   
SFG_PFC_L_3_1                             0                      0   
SFG_R_2_1                                 0                      0   
SFG_L_1_1                                 0                      0   

                      Sulcus_R_500_4  ...  MFG_DPFC_R_10_1  MFG_DPFC_L_9_1  \
Everything                         0  ...                0               0   
CSF_508_5                          1  ...                0               0   
Myelencephalon_507_5               0  ...                0               0   
Metencephalon_506_5                0  ...                0               0   
Mesencephalon_505_5                0  ...                0               0   
...                              ...  ...              ...             ...   
SFG_pole_L_5_1                     0  ...                0               0   
SFG_PFC_R_4_1                      0  ...                0               0   
SFG_PFC_L_3_1                      0  ..

In [5]:
# Clean the multilevel lookup table

multilevel = clean_multilevel(multilevel, adjacency_matrix)
multilevel

Number             Structure Immediate.parent  \
509       1            Everything              NaN   
508       2             CSF_508_5       Everything   
507       3  Myelencephalon_507_5       Everything   
506       4   Metencephalon_506_5       Everything   
505       5   Mesencephalon_505_5       Everything   
..      ...                   ...              ...   
5       505        SFG_pole_L_5_1      SFG_L_290_2   
4       506         SFG_PFC_R_4_1      SFG_R_291_2   
3       507         SFG_PFC_L_3_1      SFG_L_290_2   
2       508             SFG_R_2_1      SFG_R_291_2   
1       509             SFG_L_1_1      SFG_L_290_2   

                              Immediate.child.children  
509  Telencephalon_L_501_5, Telencephalon_R_502_5, ...  
508    Ventricle_498_4, Sulcus_L_499_4, Sulcus_R_500_4  
507     Myelencephalon_L_494_4, Myelencephalon_R_495_4  
506       Metencephalon_L_492_4, Metencephalon_R_493_4  
505       Mesencephalon_L_490_4, Mesencephalon_R_491_4  
..                                                 ...  
5                                                  NaN  
4                                                  NaN  
3                                                  NaN  
2                                                  NaN  
1                                                  NaN  

[509 rows x 4 columns]

In [6]:
# Create the subset adjacency matrix

subset_leaf_list = ["Amyg_L_73_1", "Hippo_L_75_1"]
subset = subset_matrix_creator(subset_leaf_list, adjacency_matrix, multilevel)
subset

Everything  Telencephalon_L_501_5  \
Everything                       0                      1   
Telencephalon_L_501_5            0                      0   
CerebralCortex_L_482_4           0                      0   
Limbic_L_434_3                   0                      0   
Hippo_L_338_2                    0                      0   
Amyg_L_336_2                     0                      0   
Hippo_L_75_1                     0                      0   
Amyg_L_73_1                      0                      0   

                        CerebralCortex_L_482_4  Limbic_L_434_3  Hippo_L_338_2  \
Everything                                   0               0              0   
Telencephalon_L_501_5                        1               0              0   
CerebralCortex_L_482_4                       0               1              0   
Limbic_L_434_3                               0               0              1   
Hippo_L_338_2                                0               0              0   
Amyg_L_336_2                                 0               0              0   
Hippo_L_75_1                                 0               0              0   
Amyg_L_73_1                                  0               0              0   

                        Amyg_L_336_2  Hippo_L_75_1  Amyg_L_73_1  
Everything                         0             0            0  
Telencephalon_L_501_5              0             0            0  
CerebralCortex_L_482_4             0             0            0  
Limbic_L_434_3                     1             0            0  
Hippo_L_338_2                      0             1            0  
Amyg_L_336_2                       0             0            1  
Hippo_L_75_1                       0             0            0  
Amyg_L_73_1                        0             0            0

In [7]:
# Create the descendants matrix

descendants = adjacency_descendants(subset, N=20, mu=3.0)
descendants

array([[False,  True,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [8]:
# Create the ancestors matrix

ancestors = adjacency_ancestors(subset, N=20, mu=3.0)
ancestors

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [ True,  True, False, False, False, False, False, False],
       [ True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False,  True, False, False]])

In [9]:
# Generate simulated data

generate_simulated_data(filename="test1_data.npz", subset=subset, case=1, n_repeats=10, N=20, mu=3.0)
generate_simulated_data(filename="test2_data.npz", subset=subset, case=2, n_repeats=10, N=20, mu=3.0)
generate_simulated_data(filename="test3_data.npz", subset=subset, case=3, n_repeats=10, N=20, mu=3.0)
generate_simulated_data(filename="test4_data.npz", subset=subset, case=4, n_repeats=10, N=20, mu=3.0)

# Viewing the contents of a set of generated data files to check

test1_filenames = glob("test1_data_repeat_*")
test1_filenames = sorted(test1_filenames)

for i in range(0, len(test1_filenames)):
    test = np.load(test1_filenames[i])
    print("\033[1m" + test1_filenames[i] + "\033[0m")
    print("\033[1m" + "X" + "\033[0m") 
    print(test["X"])

    print("\033[1m" + "Z" + "\033[0m") 
    print(test["Z"])

    print("\033[1m" + "G" + "\033[0m") 
    print(test["G"])
    print("\n")

test1_data_repeat_000000.npz
X
[[-1.41568311  1.07157527]
 [-0.4968568  -0.19931252]
 [ 1.29689166  1.32294207]
 [-0.1710794   1.32232216]
 [-1.37033364  0.57133733]
 [-0.29795731  0.02916697]
 [-0.59121005 -0.26611359]
 [-0.8299411   0.49421765]
 [-0.32815658  1.12926231]
 [ 1.67826447 -0.28431407]
 [-0.63307686 -0.7119629 ]
 [ 1.56710252 -0.60834028]
 [-0.34159233 -1.17137302]
 [ 0.83828994  0.50538695]
 [-0.86229265  1.37840821]
 [-0.30257746  1.99941687]
 [ 0.10487178  0.75686628]
 [ 0.69602041  1.27004657]
 [-0.41530485 -0.31667652]
 [ 0.96188511 -0.26191437]]
Z
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0

In [10]:
# Permutation testing

permutation_testing(filename_old="test1_data_repeat_*", filename_new = "test1_results.npz", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test2_data_repeat_*", filename_new = "test2_results.npz", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, clip=0.0001, initial_prob = 0.5)
permutation_testing(filename_old="test3_data_repeat_*", filename_new = "test3_results.npz", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.25, clip=0.01)
permutation_testing(filename_old="test4_data_repeat_*", filename_new = "test4_results.npz", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.75, clip=0.001)

# Viewing the contents of a set of permutation testing results files to check
# Using "\033[1m" and "\033[0m" to get bold text printed

test1_filenames = glob("test1_results_repeat_*")
test1_filenames = sorted(test1_filenames)

for i in range(0, len(test1_filenames)):
    # Assign the file to an object called "test," which is a dictionary object
    test = np.load(test1_filenames[i])
    print("\033[1m" + test1_filenames[i] + "\033[0m") 

    # Print the values corresponding to each key
    print("\033[1m" + "p-values:" + "\033[0m")
    print(test["pval"])
    
    print("\033[1m" + "names:" + "\033[0m")
    print(test["names"])
    
    print("\033[1m" + "posterior:" + "\033[0m")
    print(test["posterior"])
    
    print("\033[1m" + "strings:" + "\033[0m")
    print(test["strings"])
    print("\n")

test1_results_repeat_000000.npz
p-values:
[0.5 0.5 0.5 0.5 0.7 0.7 0.  0. ]
names:
['Limbic_L_434_3' 'CerebralCortex_L_482_4' 'Telencephalon_L_501_5'
 'Everything' 'Hippo_L_75_1' 'Hippo_L_338_2' 'Amyg_L_73_1' 'Amyg_L_336_2']
posterior:
[0.0631444  0.0631444  0.0631444  0.0631444  0.00025448 0.00025448
 0.00019906 0.00019906]
strings:
['Everything, P[Z=1|X]=0.06314439933781997, p=0.5'
 'Telencephalon_L_501_5, P[Z=1|X]=0.06314439933781997, p=0.5'
 'CerebralCortex_L_482_4, P[Z=1|X]=0.06314439933781997, p=0.5'
 'Limbic_L_434_3, P[Z=1|X]=0.06314439933781997, p=0.5'
 'Hippo_L_338_2, P[Z=1|X]=0.0002544765593550246, p=0.7'
 'Hippo_L_75_1, P[Z=1|X]=0.0002544765593550246, p=0.7'
 'Amyg_L_336_2, P[Z=1|X]=0.00019905947438347526, p=0.0'
 'Amyg_L_73_1, P[Z=1|X]=0.00019905947438347526, p=0.0']


test1_results_repeat_000001.npz
p-values:
[1.  1.  1.  1.  0.8 0.8 1.  1. ]
names:
['Limbic_L_434_3' 'CerebralCortex_L_482_4' 'Telencephalon_L_501_5'
 'Everything' 'Hippo_L_75_1' 'Hippo_L_338_2' 'Amyg_L_73_1'

In [13]:
# False positive rate

print(false_positive_rate(subset, file_names = "test1_results.npz", n_repeats = 10))
print(false_positive_rate(subset, file_names = "test2_results.npz", n_repeats = 10))
print(false_positive_rate(subset, file_names = "test3_results.npz", n_repeats = 10))
print(false_positive_rate(subset, file_names = "test4_results.npz", n_repeats = 10))

0.1
0.1
0.1
0.0


In [14]:
# Viewing the false negative rate outputs

print("\033[1m" + "Testing case 2:" + "\033[0m")
print(false_negative_rate(subset, file_names = "test2_results.npz", case=2, n_repeats=10))

print("\033[1m" + "Testing case 3:" + "\033[0m")
print(false_negative_rate(subset, file_names = "test3_results.npz", case=3, n_repeats=10))

print("\033[1m" + "Testing case 4:" + "\033[0m")
print(false_negative_rate(subset, file_names = "test4_results.npz", case=4, n_repeats=10))

Testing case 2:
                Structure  False negative rate
0              Everything                  0.9
1   Telencephalon_L_501_5                  0.9
2  CerebralCortex_L_482_4                  0.9
3          Limbic_L_434_3                  0.9
4           Hippo_L_338_2                  0.9
6            Hippo_L_75_1                  0.9
Testing case 3:
                Structure  False negative rate
0              Everything                  0.9
1   Telencephalon_L_501_5                  0.9
2  CerebralCortex_L_482_4                  0.9
3          Limbic_L_434_3                  0.9
4           Hippo_L_338_2                  0.9
5            Amyg_L_336_2                  0.9
6            Hippo_L_75_1                  0.9
7             Amyg_L_73_1                  0.9
Testing case 4:
                Structure  False negative rate
0              Everything                  1.0
1   Telencephalon_L_501_5                  1.0
2  CerebralCortex_L_482_4                  1.0
3          L

## Real test

Original parameters:

* Clip probabilities at 0.999 and 0.001
* Run 20 iterations of the EM algorithm
* Initial probabilities are 0.5
* `n_repeats = 1000` Number of repeats per case per experiment
* `n_perm = 1000` Number of permutations when permutation testing

We need to run all 4 cases so we can calculate both false positive rate and false negative rate

In [35]:
# Generate simulated data

generate_simulated_data(filename="test1_data.npz", subset=subset, case=1, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test2_data.npz", subset=subset, case=2, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test3_data.npz", subset=subset, case=3, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test4_data.npz", subset=subset, case=4, n_repeats=1000, N=20, mu=3.0)

In [ ]:
# Permutation testing

permutation_testing(filename_old="test1_data_repeat_*", filename_new = "test1_results.npz", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test2_data_repeat_*", filename_new = "test2_results.npz", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test3_data_repeat_*", filename_new = "test3_results.npz", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test4_data_repeat_*", filename_new = "test4_results.npz", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)

In [ ]:
# False positive rate

print(false_positive_rate(subset, file_names = "test2_results.npz", n_repeats = 1000))
print(false_positive_rate(subset, file_names = "test3_results.npz", n_repeats = 1000))
print(false_positive_rate(subset, file_names = "test4_results.npz", n_repeats = 1000))

In [ ]:
# False negative rate

print("\033[1m" + "Testing case 2:" + "\033[0m")
print(false_negative_rate(subset, file_names = "test2_results.npz", case=2, n_repeats=1000))

print("\033[1m" + "Testing case 3:" + "\033[0m")
print(false_negative_rate(subset, file_names = "test3_results.npz", case=3, n_repeats=1000))

print("\033[1m" + "Testing case 4:" + "\033[0m")
print(false_negative_rate(subset, file_names = "test4_results.npz", case=4, n_repeats=1000))