In [1]:
# Import libraries

import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import re

In [2]:
# Import the functions

from functions_py_file import *

In [3]:
# Read in data

adjacency_matrix = pd.read_csv("adjacency_matrix2.csv", header=0, index_col=0)

multilevel = pd.read_csv("multilevel2.csv", header=0, index_col=0) 

## Fake test

In [4]:
# Clean the adjacency matrix

adjacency_matrix = clean_adjacency_mat(adjacency_matrix)
adjacency_matrix

Everything  CSF_508_5  Myelencephalon_507_5  \
Everything                     0          1                     1   
CSF_508_5                      0          0                     0   
Myelencephalon_507_5           0          0                     0   
Metencephalon_506_5            0          0                     0   
Mesencephalon_505_5            0          0                     0   
...                          ...        ...                   ...   
SFG_pole_L_5_1                 0          0                     0   
SFG_PFC_R_4_1                  0          0                     0   
SFG_PFC_L_3_1                  0          0                     0   
SFG_R_2_1                      0          0                     0   
SFG_L_1_1                      0          0                     0   

                      Metencephalon_506_5  Mesencephalon_505_5  \
Everything                              1                    1   
CSF_508_5                               0                    0   
Myelencephalon_507_5                    0                    0   
Metencephalon_506_5                     0                    0   
Mesencephalon_505_5                     0                    0   
...                                   ...                  ...   
SFG_pole_L_5_1                          0                    0   
SFG_PFC_R_4_1                           0                    0   
SFG_PFC_L_3_1                           0                    0   
SFG_R_2_1                               0                    0   
SFG_L_1_1                               0                    0   

                      Diencephalon_R_504_5  Diencephalon_L_503_5  \
Everything                               1                     1   
CSF_508_5                                0                     0   
Myelencephalon_507_5                     0                     0   
Metencephalon_506_5                      0                     0   
Mesencephalon_505_5                      0                     0   
...                                    ...                   ...   
SFG_pole_L_5_1                           0                     0   
SFG_PFC_R_4_1                            0                     0   
SFG_PFC_L_3_1                            0                     0   
SFG_R_2_1                                0                     0   
SFG_L_1_1                                0                     0   

                      Telencephalon_R_502_5  Telencephalon_L_501_5  \
Everything                                1                      1   
CSF_508_5                                 0                      0   
Myelencephalon_507_5                      0                      0   
Metencephalon_506_5                       0                      0   
Mesencephalon_505_5                       0                      0   
...                                     ...                    ...   
SFG_pole_L_5_1                            0                      0   
SFG_PFC_R_4_1                             0                      0   
SFG_PFC_L_3_1                             0                      0   
SFG_R_2_1                                 0                      0   
SFG_L_1_1                                 0                      0   

                      Sulcus_R_500_4  ...  MFG_DPFC_R_10_1  MFG_DPFC_L_9_1  \
Everything                         0  ...                0               0   
CSF_508_5                          1  ...                0               0   
Myelencephalon_507_5               0  ...                0               0   
Metencephalon_506_5                0  ...                0               0   
Mesencephalon_505_5                0  ...                0               0   
...                              ...  ...              ...             ...   
SFG_pole_L_5_1                     0  ...                0               0   
SFG_PFC_R_4_1                      0  ...                0               0   
SFG_PFC_L_3_1                      0  ..

In [5]:
# Clean the multilevel lookup table

multilevel = clean_multilevel(multilevel, adjacency_matrix)
multilevel

Number             Structure Immediate.parent  \
509       1            Everything              NaN   
508       2             CSF_508_5       Everything   
507       3  Myelencephalon_507_5       Everything   
506       4   Metencephalon_506_5       Everything   
505       5   Mesencephalon_505_5       Everything   
..      ...                   ...              ...   
5       505        SFG_pole_L_5_1      SFG_L_290_2   
4       506         SFG_PFC_R_4_1      SFG_R_291_2   
3       507         SFG_PFC_L_3_1      SFG_L_290_2   
2       508             SFG_R_2_1      SFG_R_291_2   
1       509             SFG_L_1_1      SFG_L_290_2   

                              Immediate.child.children  
509  Telencephalon_L_501_5, Telencephalon_R_502_5, ...  
508    Ventricle_498_4, Sulcus_L_499_4, Sulcus_R_500_4  
507     Myelencephalon_L_494_4, Myelencephalon_R_495_4  
506       Metencephalon_L_492_4, Metencephalon_R_493_4  
505       Mesencephalon_L_490_4, Mesencephalon_R_491_4  
..                                                 ...  
5                                                  NaN  
4                                                  NaN  
3                                                  NaN  
2                                                  NaN  
1                                                  NaN  

[509 rows x 4 columns]

In [6]:
# Create the subset adjacency matrix

subset_leaf_list = ["Amyg_L_73_1", "Hippo_L_75_1"]
subset = subset_matrix_creator(subset_leaf_list, adjacency_matrix, multilevel)
subset

Everything  Telencephalon_L_501_5  \
Everything                       0                      1   
Telencephalon_L_501_5            0                      0   
CerebralCortex_L_482_4           0                      0   
Limbic_L_434_3                   0                      0   
Hippo_L_338_2                    0                      0   
Amyg_L_336_2                     0                      0   
Hippo_L_75_1                     0                      0   
Amyg_L_73_1                      0                      0   

                        CerebralCortex_L_482_4  Limbic_L_434_3  Hippo_L_338_2  \
Everything                                   0               0              0   
Telencephalon_L_501_5                        1               0              0   
CerebralCortex_L_482_4                       0               1              0   
Limbic_L_434_3                               0               0              1   
Hippo_L_338_2                                0               0              0   
Amyg_L_336_2                                 0               0              0   
Hippo_L_75_1                                 0               0              0   
Amyg_L_73_1                                  0               0              0   

                        Amyg_L_336_2  Hippo_L_75_1  Amyg_L_73_1  
Everything                         0             0            0  
Telencephalon_L_501_5              0             0            0  
CerebralCortex_L_482_4             0             0            0  
Limbic_L_434_3                     1             0            0  
Hippo_L_338_2                      0             1            0  
Amyg_L_336_2                       0             0            1  
Hippo_L_75_1                       0             0            0  
Amyg_L_73_1                        0             0            0

In [7]:
# Create the descendants matrix

descendants = adjacency_descendants(subset, N=20, mu=3.0)
descendants

array([[False,  True,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [8]:
# Create the ancestors matrix

ancestors = adjacency_ancestors(subset, N=20, mu=3.0)
ancestors

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [ True,  True, False, False, False, False, False, False],
       [ True,  True,  True, False, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False,  True, False, False]])

In [9]:
# Generate simulated data

generate_simulated_data(filename="test1_data", subset=subset, case=2, n_repeats=10, N=20, mu=3.0)
generate_simulated_data(filename="test2_data", subset=subset, case=3, n_repeats=5, N=20, mu=3.0)
generate_simulated_data(filename="test3_data", subset=subset, case=4, n_repeats=15, N=20, mu=3.0)
generate_simulated_data(filename="test4_data", subset=subset, case=1, n_repeats=20, N=20, mu=3.0)

# Viewing the contents of the generated data file to check
test = np.load("test1_data.npz")

print("\033[1m" + "X" + "\033[0m") 
print(test["X"])

print("\033[1m" + "Z" + "\033[0m") 
print(test["Z"])

print("\033[1m" + "G" + "\033[0m") 
print(test["G"])

X
[[ 1.80042958 -1.22491922]
 [ 2.84153295 -0.83049623]
 [ 3.51735514  2.03535429]
 [ 3.24104642  0.3107981 ]
 [ 1.85973064 -0.78355148]
 [ 2.92772529 -0.14487223]
 [ 3.16347649 -1.13529655]
 [ 4.1068043  -0.18455276]
 [ 4.50836093 -0.46738956]
 [ 2.18734538  0.06928367]
 [ 1.56324452 -1.95826173]
 [ 1.01312374  0.17955667]
 [ 0.29874523 -0.28480991]
 [-0.14888696 -0.26315714]
 [-1.23683317  0.19707747]
 [-0.28784497  0.28070207]
 [ 0.68913526  1.10393236]
 [-1.5097995  -0.30028257]
 [-0.9062396  -0.44085235]
 [-1.67475106 -1.33851997]]
Z
[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 

In [10]:
# Permutation testing

permutation_testing(filename_old="test1_data.npz", filename_new = "test1_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test2_data.npz", filename_new = "test2_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, clip=0.0001, initial_prob = 0.5)
permutation_testing(filename_old="test3_data.npz", filename_new = "test3_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.25, clip=0.01)
permutation_testing(filename_old="test4_data.npz", filename_new = "test4_results", subset=subset, n_repeats=10, nperm=10, N=20, mu=3.0, niter=5, initial_prob = 0.75, clip=0.001)

# Viewing the contents of the .npz files to check
# Using "\033[1m" and "\033[0m" to get bold text printed

filename = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"]
for i in range(0, 4):
    # Assign the file to an object called "test," which is a dictionary object
    test = np.load(filename[i])
    print("\033[1m" + filename[i] + "\033[0m") 

    # Print the values corresponding to each key
    print("\033[1m" + "p-values:" + "\033[0m")
    print(test["pval"])
    
    print("\033[1m" + "names:" + "\033[0m")
    print(test["names"])
    
    print("\033[1m" + "posterior:" + "\033[0m")
    print(test["posterior"])
    
    print("\033[1m" + "strings:" + "\033[0m")
    print(test["strings"])

test1_results.npz
p-values:
[0.  0.  0.  0.  0.  0.  0.8 0.8]
names:
['Limbic_L_434_3' 'CerebralCortex_L_482_4' 'Telencephalon_L_501_5'
 'Everything' 'Hippo_L_75_1' 'Hippo_L_338_2' 'Amyg_L_73_1' 'Amyg_L_336_2']
posterior:
[0.999908   0.999908   0.999908   0.999908   0.99990795 0.99990795
 0.00348541 0.00348541]
strings:
['Everything, P[Z=1|X]=0.9999079989195275, p=0.0'
 'Telencephalon_L_501_5, P[Z=1|X]=0.9999079989195275, p=0.0'
 'CerebralCortex_L_482_4, P[Z=1|X]=0.9999079989195275, p=0.0'
 'Limbic_L_434_3, P[Z=1|X]=0.9999079989195275, p=0.0'
 'Hippo_L_338_2, P[Z=1|X]=0.9999079528771742, p=0.0'
 'Hippo_L_75_1, P[Z=1|X]=0.9999079528771742, p=0.0'
 'Amyg_L_336_2, P[Z=1|X]=0.0034854127091254864, p=0.8'
 'Amyg_L_73_1, P[Z=1|X]=0.0034854127091254864, p=0.8']
test2_results.npz
p-values:
[0. 0. 0. 0. 0. 0. 0. 0.]
names:
['Limbic_L_434_3' 'CerebralCortex_L_482_4' 'Telencephalon_L_501_5'
 'Everything' 'Amyg_L_73_1' 'Amyg_L_336_2' 'Hippo_L_75_1' 'Hippo_L_338_2']
posterior:
[0.99999999 0.99999999

In [11]:
# False positive rate

false_positive_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], n_repeats = 10)

0.3

In [12]:
# False negative rate

print("\033[1m" + "Testing case 2:" + "\033[0m")
print(false_negative_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], case=2, n_repeats=10))

print("\033[1m" + "Testing case 3:" + "\033[0m")
print(false_negative_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], case=3, n_repeats=10))

print("\033[1m" + "Testing case 4:" + "\033[0m")
print(false_negative_rate(subset, file_names = ["test1_results.npz", "test2_results.npz", "test3_results.npz", "test4_results.npz"], case=4, n_repeats=10))

Testing case 2:
                Structure  False negative rate
0              Everything                  0.7
1   Telencephalon_L_501_5                  0.7
2  CerebralCortex_L_482_4                  0.7
3          Limbic_L_434_3                  0.7
4           Hippo_L_338_2                  0.7
6            Hippo_L_75_1                  0.7
Testing case 3:
                Structure  False negative rate
0              Everything                  0.7
1   Telencephalon_L_501_5                  0.7
2  CerebralCortex_L_482_4                  0.7
3          Limbic_L_434_3                  0.7
4           Hippo_L_338_2                  0.7
5            Amyg_L_336_2                  0.8
6            Hippo_L_75_1                  0.7
7             Amyg_L_73_1                  0.8
Testing case 4:
                Structure  False negative rate
0              Everything                  0.7
1   Telencephalon_L_501_5                  0.7
2  CerebralCortex_L_482_4                  0.7
3          L

## Real test

Original parameters:

* Clip probabilities at 0.999 and 0.001
* Run 20 iterations of the EM algorithm
* Initial probabilities are 0.5
* `n_repeats = 1000` Number of repeats per case per experiment
* `n_perm = 1000` Number of permutations when permutation testing

We need to run all 4 cases so we can calculate both false positive rate and false negative rate

In [ ]:
# Generate simulated data

generate_simulated_data(filename="test1_data", subset=subset, case=1, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test2_data", subset=subset, case=2, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test3_data", subset=subset, case=3, n_repeats=1000, N=20, mu=3.0)
generate_simulated_data(filename="test4_data", subset=subset, case=4, n_repeats=1000, N=20, mu=3.0)

In [ ]:
# Permutation testing

permutation_testing(filename_old="test1_data.npz", filename_new = "test1_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test2_data.npz", filename_new = "test2_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, clip=0.001, initial_prob = 0.5)
permutation_testing(filename_old="test3_data.npz", filename_new = "test3_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)
permutation_testing(filename_old="test4_data.npz", filename_new = "test4_results", subset=subset, n_repeats=1000, nperm=1000, N=20, mu=3.0, niter=20, initial_prob = 0.5, clip=0.001)

In [ ]:
# False positive rate

false_positive_rate(subset, file_names=["test1_results.npz"], n_repeats=1000)

In [ ]:
# False positive rate

false_positive_rate(subset, file_names=["test2_results.npz"], n_repeats=1000)

In [ ]:
# False negative rate

false_negative_rate(subset, file_names=["test2_results.npz"], case=2, n_repeats=1000)

In [ ]:
# False negative rate

false_negative_rate(subset, file_names=["test3_results.npz"], case=3, n_repeats=1000)

In [ ]:
# False negative rate

false_negative_rate(subset, file_names=["test4_results.npz"], case=4, n_repeats=1000)